<?php

namespace Modules\Peer\Tests;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PeerTestCase extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
